---- MODULE PuzzleGame ----
\* A TLA+ Module find the solution of a valid 8-puzzle
\* - https://en.wikipedia.org/wiki/15_puzzle
\* Generated by Gemini
EXTENDS Integers, Sequences, FiniteSkets

\* Ideally, board configurations should be defined as CONSTANTS
\* Current implementation uses VARIABLES due to technical constraints. :-<
VARIABLES board

Indices == 0..2
Values  == 0..8

Goal == [ r \in Indices, c \in Indices |-> 
            IF (r = 2 /\ c = 2) THEN 0 ELSE r * 3 + c + 1 ]

\* Rewrite with @@ and :> operator
Init == board = [ r \in Indices, c \in Indices |-> 
                    CASE r=0 -> <<0, 8, 3>>[c+1]
                      [] r=1 -> <<4, 2, 5>>[c+1]
                      [] r=2 -> <<7, 1, 6>>[c+1] ]

FindZero == CHOOSE r \in Indices : \E c \in Indices : board[r,c] = 0
FindZeroCol == CHOOSE c \in Indices : board[FindZero, c] = 0

\* Elegant application of LET .. IN for clarity.
Move(nr, nc) ==
    LET r0 == FindZero
        c0 == FindZeroCol
    IN board' = [board EXCEPT ![r0, c0] = board[nr, nc],
                               ![nr, nc] = 0]

Next ==
    LET r0 == FindZero
        c0 == FindZeroCol
    IN \/ (r0 > 0 /\ Move(r0 - 1, c0))
       \/ (r0 < 2 /\ Move(r0 + 1, c0))
       \/ (c0 > 0 /\ Move(r0, c0 - 1))
       \/ (c0 < 2 /\ Move(r0, c0 + 1))

\* Goal condition defined as an Invariant.
\* An Invariant Violation trace represents the path to the solution.
NotSolved == board /= Goal

====